apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-server
        image: bulutmf/us:latest  # Adjust this to your image name
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-server
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
  selector:
    app: user-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-server
  template:
    metadata:
      labels:
        app: fibonacci-server
    spec:
      containers:
      - name: fibonacci-server
        image: bulutmf/fs:latest  # Adjust this to your image name
        ports:
        - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-server
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30002
  selector:
    app: fibonacci-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: bulutmf/as:latest  # Adjust this to your image name
        ports:
        - containerPort: 53533

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  type: NodePort
  ports:
  - port: 53533
    nodePort: 30001
  selector:
    app: auth-server